[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pyvane"
version = "1.0"
description = "Segmentation and analysis of vascular sctructures."
readme = "readme.md"

[tool.setuptools]
packages = ["pyvane"]